services:
  - type: web
    name: tg-restaurants-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: TIMEZONE
        value: Europe/Moscow
      - key: WEBHOOK_SECRET
        value: tg
      - key: DB_PATH
        value: bot.db
